version: '3.6'

services:
  mysql-go:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goactions
      MYSQL_USER: goactions
      MYSQL_PASSWORD: goactions

volumes:
  db_data: {}